import { Inter } from "@next/font/google";
import Head from "next/head";
import styles from "@/styles/about.module.css";
import data from "../data/employee.json";
import { useState } from "react";
import Card from "../components/Card";
import Link from "next/link";

export default function About() {
  console.log(data);
  const [information, setInformation] = useState([...data.employees]);

  return (
    <>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="/">index</Link>
          </p>
        </div>
        <div className={styles.grid}>
          <div className={styles.cdescription}>
            <div className={styles.container1}>
              <p className={styles.fontstyle}>Employee 1</p>

         

              {information &&
                information.map((info, index) => {
                    if (info.firstName === "Amy") {
                    return ( <Card key={index} degree={info.firstName} font="14px" colour="#7F7CA"/>
                    );
                  }
                })}
              
              {information &&
                information.map((info, index) => {
                  if (info.department === "Software Engineer") {
                    return <Card key={index} degree={info.department} font="14px" colour="#7F7CA"/>;
                  }
                })}

                {information &&
                information.map((info, index) => {
                    if (["JavaScript,", " React", " ,Node.js"].some(item => info.techStack.includes(item)))  {
                    return <Card key={index} degree={info.techStack} font="14px" colour="#7F7CA"/>;
                  }
                })}
            </div>
          </div>

          <div className={styles.cdescription}>
            <div className={styles.container1}>
              <p className={styles.fontstyle}>Employee 2</p>

              {information &&
                information.map((info, index) => {
                  if (info.firstName === "John") {
                    return <Card key={index} degree={info.firstName} font="14px" colour="#7F7CA"/>;
                  }
                })}

              {information &&
                information.map((info, index) => {
                    if (info.department === "DevOps Engineer") {
                    return ( <Card key={index} degree={info.department} font="14px" colour="#7F7CA"/>
                    );
                  }
                })}

                {information &&
                information.map((info, index) => {
                    if (["AWS,", " Docker,", " Kubernetes"].some(item => info.techStack.includes(item)))  {
                    return <Card key={index} degree={info.techStack} font="14px" colour="#7F7CA"/>;
                  }
                })}
            </div>
          </div>

          <div className={styles.cdescription}>
            <div className={styles.container1}>
              <p className={styles.fontstyle}>Employee 3</p>

              {information &&
                information.map((info, index) => {
                  if (info.firstName === "Evelyn") {
                    return <Card key={index} degree={info.firstName} font="14px" colour="#7F7CA"/>;
                  }
                })}

              {information &&
                information.map((info, index) => {
                    if (info.department === "Data Scientist") { 
                    return ( <Card key={index} degree={info.department} font="14px" colour="#7F7CA"/>
                    );
                  }
                })}

                {information &&
                information.map((info, index) => {
                    if (["Python,", " TensorFlow,", " Scikit-learn"].some(item => info.techStack.includes(item)))  {
                    return <Card key={index} degree={info.techStack} font="14px" colour="#7F7CA"/>;
                  }
                })}
            </div>
          </div>


        </div>
      </main>
    </>
  );
}
